// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See VysyxSoCFull.h for the primary calling header

#ifndef VERILATED_VYSYXSOCFULL_AXI4USERYANKER_1_H_
#define VERILATED_VYSYXSOCFULL_AXI4USERYANKER_1_H_  // guard

#include "verilated_heavy.h"

//==========

class VysyxSoCFull__Syms;
class VysyxSoCFull_VerilatedVcd;


//----------

VL_MODULE(VysyxSoCFull_AXI4UserYanker_1) {
  public:

    // PORTS
    VL_IN8(clock,0,0);
    VL_IN8(reset,0,0);
    VL_OUT8(auto_in_awready,0,0);
    VL_IN8(auto_in_awvalid,0,0);
    VL_IN8(auto_in_awid,3,0);
    VL_IN8(auto_in_awlen,7,0);
    VL_IN8(auto_in_awsize,2,0);
    VL_IN8(auto_in_awburst,1,0);
    VL_IN8(auto_in_awecho_tl_state_size,3,0);
    VL_IN8(auto_in_awecho_tl_state_source,6,0);
    VL_IN8(auto_in_awecho_extra_id,0,0);
    VL_OUT8(auto_in_wready,0,0);
    VL_IN8(auto_in_wvalid,0,0);
    VL_IN8(auto_in_wstrb,7,0);
    VL_IN8(auto_in_wlast,0,0);
    VL_IN8(auto_in_bready,0,0);
    VL_OUT8(auto_in_bvalid,0,0);
    VL_OUT8(auto_in_bid,3,0);
    VL_OUT8(auto_in_bresp,1,0);
    VL_OUT8(auto_in_becho_tl_state_size,3,0);
    VL_OUT8(auto_in_becho_tl_state_source,6,0);
    VL_OUT8(auto_in_becho_extra_id,0,0);
    VL_OUT8(auto_in_arready,0,0);
    VL_IN8(auto_in_arvalid,0,0);
    VL_IN8(auto_in_arid,3,0);
    VL_IN8(auto_in_arlen,7,0);
    VL_IN8(auto_in_arsize,2,0);
    VL_IN8(auto_in_arburst,1,0);
    VL_IN8(auto_in_arecho_tl_state_size,3,0);
    VL_IN8(auto_in_arecho_tl_state_source,6,0);
    VL_IN8(auto_in_arecho_extra_id,0,0);
    VL_IN8(auto_in_rready,0,0);
    VL_OUT8(auto_in_rvalid,0,0);
    VL_OUT8(auto_in_rid,3,0);
    VL_OUT8(auto_in_rresp,1,0);
    VL_OUT8(auto_in_recho_tl_state_size,3,0);
    VL_OUT8(auto_in_recho_tl_state_source,6,0);
    VL_OUT8(auto_in_recho_extra_id,0,0);
    VL_OUT8(auto_in_rlast,0,0);
    VL_IN8(auto_out_awready,0,0);
    VL_OUT8(auto_out_awvalid,0,0);
    VL_OUT8(auto_out_awid,3,0);
    VL_OUT8(auto_out_awlen,7,0);
    VL_OUT8(auto_out_awsize,2,0);
    VL_OUT8(auto_out_awburst,1,0);
    VL_IN8(auto_out_wready,0,0);
    VL_OUT8(auto_out_wvalid,0,0);
    VL_OUT8(auto_out_wstrb,7,0);
    VL_OUT8(auto_out_wlast,0,0);
    VL_OUT8(auto_out_bready,0,0);
    VL_IN8(auto_out_bvalid,0,0);
    VL_IN8(auto_out_bid,3,0);
    VL_IN8(auto_out_bresp,1,0);
    VL_IN8(auto_out_arready,0,0);
    VL_OUT8(auto_out_arvalid,0,0);
    VL_OUT8(auto_out_arid,3,0);
    VL_OUT8(auto_out_arlen,7,0);
    VL_OUT8(auto_out_arsize,2,0);
    VL_OUT8(auto_out_arburst,1,0);
    VL_OUT8(auto_out_rready,0,0);
    VL_IN8(auto_out_rvalid,0,0);
    VL_IN8(auto_out_rid,3,0);
    VL_IN8(auto_out_rresp,1,0);
    VL_IN8(auto_out_rlast,0,0);
    VL_IN(auto_in_awaddr,31,0);
    VL_IN(auto_in_araddr,31,0);
    VL_OUT(auto_out_awaddr,31,0);
    VL_OUT(auto_out_araddr,31,0);
    VL_IN64(auto_in_wdata,63,0);
    VL_OUT64(auto_in_rdata,63,0);
    VL_OUT64(auto_out_wdata,63,0);
    VL_IN64(auto_out_rdata,63,0);

    // LOCAL SIGNALS
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        CData/*0:0*/ __PVT__QueueCompatibility_io_enq_valid;
        CData/*0:0*/ __PVT__QueueCompatibility_1_io_enq_valid;
        CData/*0:0*/ __PVT__QueueCompatibility_2_io_enq_valid;
        CData/*0:0*/ __PVT__QueueCompatibility_3_io_enq_valid;
        CData/*0:0*/ __PVT__QueueCompatibility_4_io_enq_valid;
        CData/*0:0*/ __PVT__QueueCompatibility_5_io_enq_valid;
        CData/*0:0*/ __PVT__QueueCompatibility_6_io_enq_valid;
        CData/*0:0*/ __PVT__QueueCompatibility_7_io_enq_valid;
        CData/*0:0*/ __PVT__QueueCompatibility_8_io_enq_valid;
        CData/*0:0*/ __PVT__QueueCompatibility_9_io_enq_valid;
        CData/*0:0*/ __PVT__QueueCompatibility_10_io_enq_valid;
        CData/*0:0*/ __PVT__QueueCompatibility_11_io_enq_valid;
        CData/*0:0*/ __PVT__QueueCompatibility_12_io_enq_valid;
        CData/*0:0*/ __PVT__QueueCompatibility_13_io_enq_valid;
        CData/*0:0*/ __PVT__QueueCompatibility_14_io_enq_valid;
        CData/*0:0*/ __PVT__QueueCompatibility_15_io_enq_valid;
        CData/*0:0*/ __PVT__QueueCompatibility_16_io_enq_valid;
        CData/*0:0*/ __PVT__QueueCompatibility_17_io_enq_valid;
        CData/*0:0*/ __PVT__QueueCompatibility_18_io_enq_valid;
        CData/*0:0*/ __PVT__QueueCompatibility_19_io_enq_valid;
        CData/*0:0*/ __PVT__QueueCompatibility_20_io_enq_valid;
        CData/*0:0*/ __PVT__QueueCompatibility_21_io_enq_valid;
        CData/*0:0*/ __PVT__QueueCompatibility_22_io_enq_valid;
        CData/*0:0*/ __PVT__QueueCompatibility_23_io_enq_valid;
        CData/*0:0*/ __PVT__QueueCompatibility_24_io_enq_valid;
        CData/*0:0*/ __PVT__QueueCompatibility_25_io_enq_valid;
        CData/*0:0*/ __PVT__QueueCompatibility_26_io_enq_valid;
        CData/*0:0*/ __PVT__QueueCompatibility_27_io_enq_valid;
        CData/*0:0*/ __PVT__QueueCompatibility_28_io_enq_valid;
        CData/*0:0*/ __PVT__QueueCompatibility_29_io_enq_valid;
        CData/*0:0*/ __PVT__QueueCompatibility_30_io_enq_valid;
        CData/*0:0*/ __PVT__QueueCompatibility_31_io_enq_valid;
        CData/*0:0*/ __PVT___GEN_10;
        CData/*0:0*/ __PVT___GEN_15;
        CData/*0:0*/ __PVT___GEN_43;
        CData/*0:0*/ __PVT___GEN_90;
        CData/*0:0*/ __PVT___GEN_95;
        CData/*0:0*/ __PVT___GEN_123;
        CData/*3:0*/ __PVT__QueueCompatibility__DOT__ram_tl_state_size_io_deq_bits_MPORT_data;
        CData/*6:0*/ __PVT__QueueCompatibility__DOT__ram_tl_state_source_io_deq_bits_MPORT_data;
        CData/*4:0*/ __PVT__QueueCompatibility__DOT__enq_ptr_value;
        CData/*4:0*/ __PVT__QueueCompatibility__DOT__deq_ptr_value;
        CData/*0:0*/ __PVT__QueueCompatibility__DOT__maybe_full;
        CData/*0:0*/ __PVT__QueueCompatibility__DOT__ptr_match;
        CData/*0:0*/ __PVT__QueueCompatibility__DOT__empty;
        CData/*0:0*/ __PVT__QueueCompatibility__DOT__full;
        CData/*0:0*/ __PVT__QueueCompatibility__DOT__do_enq;
        CData/*0:0*/ __PVT__QueueCompatibility__DOT__do_deq;
        CData/*0:0*/ __PVT__QueueCompatibility__DOT__wrap;
        CData/*4:0*/ __PVT__QueueCompatibility__DOT___value_T_1;
        CData/*0:0*/ __PVT__QueueCompatibility__DOT__wrap_1;
        CData/*4:0*/ __PVT__QueueCompatibility__DOT___value_T_3;
        CData/*4:0*/ __PVT__QueueCompatibility_1__DOT__enq_ptr_value;
        CData/*4:0*/ __PVT__QueueCompatibility_1__DOT__deq_ptr_value;
        CData/*0:0*/ __PVT__QueueCompatibility_1__DOT__maybe_full;
        CData/*0:0*/ __PVT__QueueCompatibility_1__DOT__ptr_match;
        CData/*0:0*/ __PVT__QueueCompatibility_1__DOT__empty;
        CData/*0:0*/ __PVT__QueueCompatibility_1__DOT__full;
        CData/*0:0*/ __PVT__QueueCompatibility_1__DOT__do_enq;
        CData/*0:0*/ __PVT__QueueCompatibility_1__DOT__do_deq;
        CData/*0:0*/ __PVT__QueueCompatibility_1__DOT__wrap;
        CData/*4:0*/ __PVT__QueueCompatibility_1__DOT___value_T_1;
        CData/*0:0*/ __PVT__QueueCompatibility_1__DOT__wrap_1;
        CData/*4:0*/ __PVT__QueueCompatibility_1__DOT___value_T_3;
    };
    struct {
        CData/*4:0*/ __PVT__QueueCompatibility_2__DOT__enq_ptr_value;
        CData/*4:0*/ __PVT__QueueCompatibility_2__DOT__deq_ptr_value;
        CData/*0:0*/ __PVT__QueueCompatibility_2__DOT__maybe_full;
        CData/*0:0*/ __PVT__QueueCompatibility_2__DOT__ptr_match;
        CData/*0:0*/ __PVT__QueueCompatibility_2__DOT__empty;
        CData/*0:0*/ __PVT__QueueCompatibility_2__DOT__full;
        CData/*0:0*/ __PVT__QueueCompatibility_2__DOT__do_enq;
        CData/*0:0*/ __PVT__QueueCompatibility_2__DOT__do_deq;
        CData/*0:0*/ __PVT__QueueCompatibility_2__DOT__wrap;
        CData/*4:0*/ __PVT__QueueCompatibility_2__DOT___value_T_1;
        CData/*0:0*/ __PVT__QueueCompatibility_2__DOT__wrap_1;
        CData/*4:0*/ __PVT__QueueCompatibility_2__DOT___value_T_3;
        CData/*4:0*/ __PVT__QueueCompatibility_3__DOT__enq_ptr_value;
        CData/*4:0*/ __PVT__QueueCompatibility_3__DOT__deq_ptr_value;
        CData/*0:0*/ __PVT__QueueCompatibility_3__DOT__maybe_full;
        CData/*0:0*/ __PVT__QueueCompatibility_3__DOT__ptr_match;
        CData/*0:0*/ __PVT__QueueCompatibility_3__DOT__empty;
        CData/*0:0*/ __PVT__QueueCompatibility_3__DOT__full;
        CData/*0:0*/ __PVT__QueueCompatibility_3__DOT__do_enq;
        CData/*0:0*/ __PVT__QueueCompatibility_3__DOT__do_deq;
        CData/*0:0*/ __PVT__QueueCompatibility_3__DOT__wrap;
        CData/*4:0*/ __PVT__QueueCompatibility_3__DOT___value_T_1;
        CData/*0:0*/ __PVT__QueueCompatibility_3__DOT__wrap_1;
        CData/*4:0*/ __PVT__QueueCompatibility_3__DOT___value_T_3;
        CData/*4:0*/ __PVT__QueueCompatibility_4__DOT__enq_ptr_value;
        CData/*4:0*/ __PVT__QueueCompatibility_4__DOT__deq_ptr_value;
        CData/*0:0*/ __PVT__QueueCompatibility_4__DOT__maybe_full;
        CData/*0:0*/ __PVT__QueueCompatibility_4__DOT__ptr_match;
        CData/*0:0*/ __PVT__QueueCompatibility_4__DOT__empty;
        CData/*0:0*/ __PVT__QueueCompatibility_4__DOT__full;
        CData/*0:0*/ __PVT__QueueCompatibility_4__DOT__do_enq;
        CData/*0:0*/ __PVT__QueueCompatibility_4__DOT__do_deq;
        CData/*0:0*/ __PVT__QueueCompatibility_4__DOT__wrap;
        CData/*4:0*/ __PVT__QueueCompatibility_4__DOT___value_T_1;
        CData/*0:0*/ __PVT__QueueCompatibility_4__DOT__wrap_1;
        CData/*4:0*/ __PVT__QueueCompatibility_4__DOT___value_T_3;
        CData/*4:0*/ __PVT__QueueCompatibility_5__DOT__enq_ptr_value;
        CData/*4:0*/ __PVT__QueueCompatibility_5__DOT__deq_ptr_value;
        CData/*0:0*/ __PVT__QueueCompatibility_5__DOT__maybe_full;
        CData/*0:0*/ __PVT__QueueCompatibility_5__DOT__ptr_match;
        CData/*0:0*/ __PVT__QueueCompatibility_5__DOT__empty;
        CData/*0:0*/ __PVT__QueueCompatibility_5__DOT__full;
        CData/*0:0*/ __PVT__QueueCompatibility_5__DOT__do_enq;
        CData/*0:0*/ __PVT__QueueCompatibility_5__DOT__do_deq;
        CData/*0:0*/ __PVT__QueueCompatibility_5__DOT__wrap;
        CData/*4:0*/ __PVT__QueueCompatibility_5__DOT___value_T_1;
        CData/*0:0*/ __PVT__QueueCompatibility_5__DOT__wrap_1;
        CData/*4:0*/ __PVT__QueueCompatibility_5__DOT___value_T_3;
        CData/*4:0*/ __PVT__QueueCompatibility_6__DOT__enq_ptr_value;
        CData/*4:0*/ __PVT__QueueCompatibility_6__DOT__deq_ptr_value;
        CData/*0:0*/ __PVT__QueueCompatibility_6__DOT__maybe_full;
        CData/*0:0*/ __PVT__QueueCompatibility_6__DOT__ptr_match;
        CData/*0:0*/ __PVT__QueueCompatibility_6__DOT__empty;
        CData/*0:0*/ __PVT__QueueCompatibility_6__DOT__full;
        CData/*0:0*/ __PVT__QueueCompatibility_6__DOT__do_enq;
        CData/*0:0*/ __PVT__QueueCompatibility_6__DOT__do_deq;
        CData/*0:0*/ __PVT__QueueCompatibility_6__DOT__wrap;
        CData/*4:0*/ __PVT__QueueCompatibility_6__DOT___value_T_1;
        CData/*0:0*/ __PVT__QueueCompatibility_6__DOT__wrap_1;
        CData/*4:0*/ __PVT__QueueCompatibility_6__DOT___value_T_3;
        CData/*0:0*/ __PVT__QueueCompatibility_7__DOT__maybe_full;
        CData/*0:0*/ __PVT__QueueCompatibility_7__DOT__do_enq;
        CData/*0:0*/ __PVT__QueueCompatibility_7__DOT__do_deq;
        CData/*0:0*/ __PVT__QueueCompatibility_8__DOT__maybe_full;
    };
    struct {
        CData/*0:0*/ __PVT__QueueCompatibility_8__DOT__do_enq;
        CData/*0:0*/ __PVT__QueueCompatibility_8__DOT__do_deq;
        CData/*0:0*/ __PVT__QueueCompatibility_9__DOT__maybe_full;
        CData/*0:0*/ __PVT__QueueCompatibility_9__DOT__do_enq;
        CData/*0:0*/ __PVT__QueueCompatibility_9__DOT__do_deq;
        CData/*0:0*/ __PVT__QueueCompatibility_10__DOT__maybe_full;
        CData/*0:0*/ __PVT__QueueCompatibility_10__DOT__do_enq;
        CData/*0:0*/ __PVT__QueueCompatibility_10__DOT__do_deq;
        CData/*0:0*/ __PVT__QueueCompatibility_11__DOT__maybe_full;
        CData/*0:0*/ __PVT__QueueCompatibility_11__DOT__do_enq;
        CData/*0:0*/ __PVT__QueueCompatibility_11__DOT__do_deq;
        CData/*0:0*/ __PVT__QueueCompatibility_12__DOT__maybe_full;
        CData/*0:0*/ __PVT__QueueCompatibility_12__DOT__do_enq;
        CData/*0:0*/ __PVT__QueueCompatibility_12__DOT__do_deq;
        CData/*0:0*/ __PVT__QueueCompatibility_13__DOT__maybe_full;
        CData/*0:0*/ __PVT__QueueCompatibility_13__DOT__do_enq;
        CData/*0:0*/ __PVT__QueueCompatibility_13__DOT__do_deq;
        CData/*0:0*/ __PVT__QueueCompatibility_14__DOT__maybe_full;
        CData/*0:0*/ __PVT__QueueCompatibility_14__DOT__do_enq;
        CData/*0:0*/ __PVT__QueueCompatibility_14__DOT__do_deq;
        CData/*0:0*/ __PVT__QueueCompatibility_15__DOT__maybe_full;
        CData/*0:0*/ __PVT__QueueCompatibility_15__DOT__do_enq;
        CData/*0:0*/ __PVT__QueueCompatibility_15__DOT__do_deq;
        CData/*3:0*/ __PVT__QueueCompatibility_16__DOT__ram_tl_state_size_io_deq_bits_MPORT_data;
        CData/*6:0*/ __PVT__QueueCompatibility_16__DOT__ram_tl_state_source_io_deq_bits_MPORT_data;
        CData/*4:0*/ __PVT__QueueCompatibility_16__DOT__enq_ptr_value;
        CData/*4:0*/ __PVT__QueueCompatibility_16__DOT__deq_ptr_value;
        CData/*0:0*/ __PVT__QueueCompatibility_16__DOT__maybe_full;
        CData/*0:0*/ __PVT__QueueCompatibility_16__DOT__ptr_match;
        CData/*0:0*/ __PVT__QueueCompatibility_16__DOT__empty;
        CData/*0:0*/ __PVT__QueueCompatibility_16__DOT__full;
        CData/*0:0*/ __PVT__QueueCompatibility_16__DOT__do_enq;
        CData/*0:0*/ __PVT__QueueCompatibility_16__DOT__do_deq;
        CData/*0:0*/ __PVT__QueueCompatibility_16__DOT__wrap;
        CData/*4:0*/ __PVT__QueueCompatibility_16__DOT___value_T_1;
        CData/*0:0*/ __PVT__QueueCompatibility_16__DOT__wrap_1;
        CData/*4:0*/ __PVT__QueueCompatibility_16__DOT___value_T_3;
        CData/*4:0*/ __PVT__QueueCompatibility_17__DOT__enq_ptr_value;
        CData/*4:0*/ __PVT__QueueCompatibility_17__DOT__deq_ptr_value;
        CData/*0:0*/ __PVT__QueueCompatibility_17__DOT__maybe_full;
        CData/*0:0*/ __PVT__QueueCompatibility_17__DOT__ptr_match;
        CData/*0:0*/ __PVT__QueueCompatibility_17__DOT__empty;
        CData/*0:0*/ __PVT__QueueCompatibility_17__DOT__full;
        CData/*0:0*/ __PVT__QueueCompatibility_17__DOT__do_enq;
        CData/*0:0*/ __PVT__QueueCompatibility_17__DOT__do_deq;
        CData/*0:0*/ __PVT__QueueCompatibility_17__DOT__wrap;
        CData/*4:0*/ __PVT__QueueCompatibility_17__DOT___value_T_1;
        CData/*0:0*/ __PVT__QueueCompatibility_17__DOT__wrap_1;
        CData/*4:0*/ __PVT__QueueCompatibility_17__DOT___value_T_3;
        CData/*4:0*/ __PVT__QueueCompatibility_18__DOT__enq_ptr_value;
        CData/*4:0*/ __PVT__QueueCompatibility_18__DOT__deq_ptr_value;
        CData/*0:0*/ __PVT__QueueCompatibility_18__DOT__maybe_full;
        CData/*0:0*/ __PVT__QueueCompatibility_18__DOT__ptr_match;
        CData/*0:0*/ __PVT__QueueCompatibility_18__DOT__empty;
        CData/*0:0*/ __PVT__QueueCompatibility_18__DOT__full;
        CData/*0:0*/ __PVT__QueueCompatibility_18__DOT__do_enq;
        CData/*0:0*/ __PVT__QueueCompatibility_18__DOT__do_deq;
        CData/*0:0*/ __PVT__QueueCompatibility_18__DOT__wrap;
        CData/*4:0*/ __PVT__QueueCompatibility_18__DOT___value_T_1;
        CData/*0:0*/ __PVT__QueueCompatibility_18__DOT__wrap_1;
        CData/*4:0*/ __PVT__QueueCompatibility_18__DOT___value_T_3;
        CData/*4:0*/ __PVT__QueueCompatibility_19__DOT__enq_ptr_value;
        CData/*4:0*/ __PVT__QueueCompatibility_19__DOT__deq_ptr_value;
        CData/*0:0*/ __PVT__QueueCompatibility_19__DOT__maybe_full;
    };
    struct {
        CData/*0:0*/ __PVT__QueueCompatibility_19__DOT__ptr_match;
        CData/*0:0*/ __PVT__QueueCompatibility_19__DOT__empty;
        CData/*0:0*/ __PVT__QueueCompatibility_19__DOT__full;
        CData/*0:0*/ __PVT__QueueCompatibility_19__DOT__do_enq;
        CData/*0:0*/ __PVT__QueueCompatibility_19__DOT__do_deq;
        CData/*0:0*/ __PVT__QueueCompatibility_19__DOT__wrap;
        CData/*4:0*/ __PVT__QueueCompatibility_19__DOT___value_T_1;
        CData/*0:0*/ __PVT__QueueCompatibility_19__DOT__wrap_1;
        CData/*4:0*/ __PVT__QueueCompatibility_19__DOT___value_T_3;
        CData/*4:0*/ __PVT__QueueCompatibility_20__DOT__enq_ptr_value;
        CData/*4:0*/ __PVT__QueueCompatibility_20__DOT__deq_ptr_value;
        CData/*0:0*/ __PVT__QueueCompatibility_20__DOT__maybe_full;
        CData/*0:0*/ __PVT__QueueCompatibility_20__DOT__ptr_match;
        CData/*0:0*/ __PVT__QueueCompatibility_20__DOT__empty;
        CData/*0:0*/ __PVT__QueueCompatibility_20__DOT__full;
        CData/*0:0*/ __PVT__QueueCompatibility_20__DOT__do_enq;
        CData/*0:0*/ __PVT__QueueCompatibility_20__DOT__do_deq;
        CData/*0:0*/ __PVT__QueueCompatibility_20__DOT__wrap;
        CData/*4:0*/ __PVT__QueueCompatibility_20__DOT___value_T_1;
        CData/*0:0*/ __PVT__QueueCompatibility_20__DOT__wrap_1;
        CData/*4:0*/ __PVT__QueueCompatibility_20__DOT___value_T_3;
        CData/*4:0*/ __PVT__QueueCompatibility_21__DOT__enq_ptr_value;
        CData/*4:0*/ __PVT__QueueCompatibility_21__DOT__deq_ptr_value;
        CData/*0:0*/ __PVT__QueueCompatibility_21__DOT__maybe_full;
        CData/*0:0*/ __PVT__QueueCompatibility_21__DOT__ptr_match;
        CData/*0:0*/ __PVT__QueueCompatibility_21__DOT__empty;
        CData/*0:0*/ __PVT__QueueCompatibility_21__DOT__full;
        CData/*0:0*/ __PVT__QueueCompatibility_21__DOT__do_enq;
        CData/*0:0*/ __PVT__QueueCompatibility_21__DOT__do_deq;
        CData/*0:0*/ __PVT__QueueCompatibility_21__DOT__wrap;
        CData/*4:0*/ __PVT__QueueCompatibility_21__DOT___value_T_1;
        CData/*0:0*/ __PVT__QueueCompatibility_21__DOT__wrap_1;
        CData/*4:0*/ __PVT__QueueCompatibility_21__DOT___value_T_3;
        CData/*4:0*/ __PVT__QueueCompatibility_22__DOT__enq_ptr_value;
        CData/*4:0*/ __PVT__QueueCompatibility_22__DOT__deq_ptr_value;
        CData/*0:0*/ __PVT__QueueCompatibility_22__DOT__maybe_full;
        CData/*0:0*/ __PVT__QueueCompatibility_22__DOT__ptr_match;
        CData/*0:0*/ __PVT__QueueCompatibility_22__DOT__empty;
        CData/*0:0*/ __PVT__QueueCompatibility_22__DOT__full;
        CData/*0:0*/ __PVT__QueueCompatibility_22__DOT__do_enq;
        CData/*0:0*/ __PVT__QueueCompatibility_22__DOT__do_deq;
        CData/*0:0*/ __PVT__QueueCompatibility_22__DOT__wrap;
        CData/*4:0*/ __PVT__QueueCompatibility_22__DOT___value_T_1;
        CData/*0:0*/ __PVT__QueueCompatibility_22__DOT__wrap_1;
        CData/*4:0*/ __PVT__QueueCompatibility_22__DOT___value_T_3;
        CData/*0:0*/ __PVT__QueueCompatibility_23__DOT__maybe_full;
        CData/*0:0*/ __PVT__QueueCompatibility_23__DOT__do_enq;
        CData/*0:0*/ __PVT__QueueCompatibility_23__DOT__do_deq;
        CData/*0:0*/ __PVT__QueueCompatibility_24__DOT__maybe_full;
        CData/*0:0*/ __PVT__QueueCompatibility_24__DOT__do_enq;
        CData/*0:0*/ __PVT__QueueCompatibility_24__DOT__do_deq;
        CData/*0:0*/ __PVT__QueueCompatibility_25__DOT__maybe_full;
        CData/*0:0*/ __PVT__QueueCompatibility_25__DOT__do_enq;
        CData/*0:0*/ __PVT__QueueCompatibility_25__DOT__do_deq;
        CData/*0:0*/ __PVT__QueueCompatibility_26__DOT__maybe_full;
        CData/*0:0*/ __PVT__QueueCompatibility_26__DOT__do_enq;
        CData/*0:0*/ __PVT__QueueCompatibility_26__DOT__do_deq;
        CData/*0:0*/ __PVT__QueueCompatibility_27__DOT__maybe_full;
        CData/*0:0*/ __PVT__QueueCompatibility_27__DOT__do_enq;
        CData/*0:0*/ __PVT__QueueCompatibility_27__DOT__do_deq;
        CData/*0:0*/ __PVT__QueueCompatibility_28__DOT__maybe_full;
        CData/*0:0*/ __PVT__QueueCompatibility_28__DOT__do_enq;
        CData/*0:0*/ __PVT__QueueCompatibility_28__DOT__do_deq;
        CData/*0:0*/ __PVT__QueueCompatibility_29__DOT__maybe_full;
    };
    struct {
        CData/*0:0*/ __PVT__QueueCompatibility_29__DOT__do_enq;
        CData/*0:0*/ __PVT__QueueCompatibility_29__DOT__do_deq;
        CData/*0:0*/ __PVT__QueueCompatibility_30__DOT__maybe_full;
        CData/*0:0*/ __PVT__QueueCompatibility_30__DOT__do_enq;
        CData/*0:0*/ __PVT__QueueCompatibility_30__DOT__do_deq;
        CData/*0:0*/ __PVT__QueueCompatibility_31__DOT__maybe_full;
        CData/*0:0*/ __PVT__QueueCompatibility_31__DOT__do_enq;
        CData/*0:0*/ __PVT__QueueCompatibility_31__DOT__do_deq;
        VlUnpacked<CData/*3:0*/, 17> __PVT__QueueCompatibility__DOT__ram_tl_state_size;
        VlUnpacked<CData/*6:0*/, 17> __PVT__QueueCompatibility__DOT__ram_tl_state_source;
        VlUnpacked<CData/*0:0*/, 17> __PVT__QueueCompatibility__DOT__ram_extra_id;
        VlUnpacked<CData/*3:0*/, 17> __PVT__QueueCompatibility_1__DOT__ram_tl_state_size;
        VlUnpacked<CData/*6:0*/, 17> __PVT__QueueCompatibility_1__DOT__ram_tl_state_source;
        VlUnpacked<CData/*0:0*/, 17> __PVT__QueueCompatibility_1__DOT__ram_extra_id;
        VlUnpacked<CData/*3:0*/, 17> __PVT__QueueCompatibility_2__DOT__ram_tl_state_size;
        VlUnpacked<CData/*6:0*/, 17> __PVT__QueueCompatibility_2__DOT__ram_tl_state_source;
        VlUnpacked<CData/*0:0*/, 17> __PVT__QueueCompatibility_2__DOT__ram_extra_id;
        VlUnpacked<CData/*3:0*/, 17> __PVT__QueueCompatibility_3__DOT__ram_tl_state_size;
        VlUnpacked<CData/*6:0*/, 17> __PVT__QueueCompatibility_3__DOT__ram_tl_state_source;
        VlUnpacked<CData/*0:0*/, 17> __PVT__QueueCompatibility_3__DOT__ram_extra_id;
        VlUnpacked<CData/*3:0*/, 17> __PVT__QueueCompatibility_4__DOT__ram_tl_state_size;
        VlUnpacked<CData/*6:0*/, 17> __PVT__QueueCompatibility_4__DOT__ram_tl_state_source;
        VlUnpacked<CData/*0:0*/, 17> __PVT__QueueCompatibility_4__DOT__ram_extra_id;
        VlUnpacked<CData/*3:0*/, 17> __PVT__QueueCompatibility_5__DOT__ram_tl_state_size;
        VlUnpacked<CData/*6:0*/, 17> __PVT__QueueCompatibility_5__DOT__ram_tl_state_source;
        VlUnpacked<CData/*0:0*/, 17> __PVT__QueueCompatibility_5__DOT__ram_extra_id;
        VlUnpacked<CData/*3:0*/, 17> __PVT__QueueCompatibility_6__DOT__ram_tl_state_size;
        VlUnpacked<CData/*6:0*/, 17> __PVT__QueueCompatibility_6__DOT__ram_tl_state_source;
        VlUnpacked<CData/*0:0*/, 17> __PVT__QueueCompatibility_6__DOT__ram_extra_id;
        VlUnpacked<CData/*3:0*/, 1> __PVT__QueueCompatibility_7__DOT__ram_tl_state_size;
        VlUnpacked<CData/*6:0*/, 1> __PVT__QueueCompatibility_7__DOT__ram_tl_state_source;
        VlUnpacked<CData/*0:0*/, 1> __PVT__QueueCompatibility_7__DOT__ram_extra_id;
        VlUnpacked<CData/*3:0*/, 1> __PVT__QueueCompatibility_8__DOT__ram_tl_state_size;
        VlUnpacked<CData/*6:0*/, 1> __PVT__QueueCompatibility_8__DOT__ram_tl_state_source;
        VlUnpacked<CData/*0:0*/, 1> __PVT__QueueCompatibility_8__DOT__ram_extra_id;
        VlUnpacked<CData/*3:0*/, 1> __PVT__QueueCompatibility_9__DOT__ram_tl_state_size;
        VlUnpacked<CData/*6:0*/, 1> __PVT__QueueCompatibility_9__DOT__ram_tl_state_source;
        VlUnpacked<CData/*0:0*/, 1> __PVT__QueueCompatibility_9__DOT__ram_extra_id;
        VlUnpacked<CData/*3:0*/, 1> __PVT__QueueCompatibility_10__DOT__ram_tl_state_size;
        VlUnpacked<CData/*6:0*/, 1> __PVT__QueueCompatibility_10__DOT__ram_tl_state_source;
        VlUnpacked<CData/*0:0*/, 1> __PVT__QueueCompatibility_10__DOT__ram_extra_id;
        VlUnpacked<CData/*3:0*/, 1> __PVT__QueueCompatibility_11__DOT__ram_tl_state_size;
        VlUnpacked<CData/*6:0*/, 1> __PVT__QueueCompatibility_11__DOT__ram_tl_state_source;
        VlUnpacked<CData/*0:0*/, 1> __PVT__QueueCompatibility_11__DOT__ram_extra_id;
        VlUnpacked<CData/*3:0*/, 1> __PVT__QueueCompatibility_12__DOT__ram_tl_state_size;
        VlUnpacked<CData/*6:0*/, 1> __PVT__QueueCompatibility_12__DOT__ram_tl_state_source;
        VlUnpacked<CData/*0:0*/, 1> __PVT__QueueCompatibility_12__DOT__ram_extra_id;
        VlUnpacked<CData/*3:0*/, 1> __PVT__QueueCompatibility_13__DOT__ram_tl_state_size;
        VlUnpacked<CData/*6:0*/, 1> __PVT__QueueCompatibility_13__DOT__ram_tl_state_source;
        VlUnpacked<CData/*0:0*/, 1> __PVT__QueueCompatibility_13__DOT__ram_extra_id;
        VlUnpacked<CData/*3:0*/, 1> __PVT__QueueCompatibility_14__DOT__ram_tl_state_size;
        VlUnpacked<CData/*6:0*/, 1> __PVT__QueueCompatibility_14__DOT__ram_tl_state_source;
        VlUnpacked<CData/*0:0*/, 1> __PVT__QueueCompatibility_14__DOT__ram_extra_id;
        VlUnpacked<CData/*3:0*/, 1> __PVT__QueueCompatibility_15__DOT__ram_tl_state_size;
        VlUnpacked<CData/*6:0*/, 1> __PVT__QueueCompatibility_15__DOT__ram_tl_state_source;
        VlUnpacked<CData/*0:0*/, 1> __PVT__QueueCompatibility_15__DOT__ram_extra_id;
        VlUnpacked<CData/*3:0*/, 17> __PVT__QueueCompatibility_16__DOT__ram_tl_state_size;
        VlUnpacked<CData/*6:0*/, 17> __PVT__QueueCompatibility_16__DOT__ram_tl_state_source;
        VlUnpacked<CData/*0:0*/, 17> __PVT__QueueCompatibility_16__DOT__ram_extra_id;
        VlUnpacked<CData/*3:0*/, 17> __PVT__QueueCompatibility_17__DOT__ram_tl_state_size;
        VlUnpacked<CData/*6:0*/, 17> __PVT__QueueCompatibility_17__DOT__ram_tl_state_source;
        VlUnpacked<CData/*0:0*/, 17> __PVT__QueueCompatibility_17__DOT__ram_extra_id;
        VlUnpacked<CData/*3:0*/, 17> __PVT__QueueCompatibility_18__DOT__ram_tl_state_size;
        VlUnpacked<CData/*6:0*/, 17> __PVT__QueueCompatibility_18__DOT__ram_tl_state_source;
    };
    struct {
        VlUnpacked<CData/*0:0*/, 17> __PVT__QueueCompatibility_18__DOT__ram_extra_id;
        VlUnpacked<CData/*3:0*/, 17> __PVT__QueueCompatibility_19__DOT__ram_tl_state_size;
        VlUnpacked<CData/*6:0*/, 17> __PVT__QueueCompatibility_19__DOT__ram_tl_state_source;
        VlUnpacked<CData/*0:0*/, 17> __PVT__QueueCompatibility_19__DOT__ram_extra_id;
        VlUnpacked<CData/*3:0*/, 17> __PVT__QueueCompatibility_20__DOT__ram_tl_state_size;
        VlUnpacked<CData/*6:0*/, 17> __PVT__QueueCompatibility_20__DOT__ram_tl_state_source;
        VlUnpacked<CData/*0:0*/, 17> __PVT__QueueCompatibility_20__DOT__ram_extra_id;
        VlUnpacked<CData/*3:0*/, 17> __PVT__QueueCompatibility_21__DOT__ram_tl_state_size;
        VlUnpacked<CData/*6:0*/, 17> __PVT__QueueCompatibility_21__DOT__ram_tl_state_source;
        VlUnpacked<CData/*0:0*/, 17> __PVT__QueueCompatibility_21__DOT__ram_extra_id;
        VlUnpacked<CData/*3:0*/, 17> __PVT__QueueCompatibility_22__DOT__ram_tl_state_size;
        VlUnpacked<CData/*6:0*/, 17> __PVT__QueueCompatibility_22__DOT__ram_tl_state_source;
        VlUnpacked<CData/*0:0*/, 17> __PVT__QueueCompatibility_22__DOT__ram_extra_id;
        VlUnpacked<CData/*3:0*/, 1> __PVT__QueueCompatibility_23__DOT__ram_tl_state_size;
        VlUnpacked<CData/*6:0*/, 1> __PVT__QueueCompatibility_23__DOT__ram_tl_state_source;
        VlUnpacked<CData/*0:0*/, 1> __PVT__QueueCompatibility_23__DOT__ram_extra_id;
        VlUnpacked<CData/*3:0*/, 1> __PVT__QueueCompatibility_24__DOT__ram_tl_state_size;
        VlUnpacked<CData/*6:0*/, 1> __PVT__QueueCompatibility_24__DOT__ram_tl_state_source;
        VlUnpacked<CData/*0:0*/, 1> __PVT__QueueCompatibility_24__DOT__ram_extra_id;
        VlUnpacked<CData/*3:0*/, 1> __PVT__QueueCompatibility_25__DOT__ram_tl_state_size;
        VlUnpacked<CData/*6:0*/, 1> __PVT__QueueCompatibility_25__DOT__ram_tl_state_source;
        VlUnpacked<CData/*0:0*/, 1> __PVT__QueueCompatibility_25__DOT__ram_extra_id;
        VlUnpacked<CData/*3:0*/, 1> __PVT__QueueCompatibility_26__DOT__ram_tl_state_size;
        VlUnpacked<CData/*6:0*/, 1> __PVT__QueueCompatibility_26__DOT__ram_tl_state_source;
        VlUnpacked<CData/*0:0*/, 1> __PVT__QueueCompatibility_26__DOT__ram_extra_id;
        VlUnpacked<CData/*3:0*/, 1> __PVT__QueueCompatibility_27__DOT__ram_tl_state_size;
        VlUnpacked<CData/*6:0*/, 1> __PVT__QueueCompatibility_27__DOT__ram_tl_state_source;
        VlUnpacked<CData/*0:0*/, 1> __PVT__QueueCompatibility_27__DOT__ram_extra_id;
        VlUnpacked<CData/*3:0*/, 1> __PVT__QueueCompatibility_28__DOT__ram_tl_state_size;
        VlUnpacked<CData/*6:0*/, 1> __PVT__QueueCompatibility_28__DOT__ram_tl_state_source;
        VlUnpacked<CData/*0:0*/, 1> __PVT__QueueCompatibility_28__DOT__ram_extra_id;
        VlUnpacked<CData/*3:0*/, 1> __PVT__QueueCompatibility_29__DOT__ram_tl_state_size;
        VlUnpacked<CData/*6:0*/, 1> __PVT__QueueCompatibility_29__DOT__ram_tl_state_source;
        VlUnpacked<CData/*0:0*/, 1> __PVT__QueueCompatibility_29__DOT__ram_extra_id;
        VlUnpacked<CData/*3:0*/, 1> __PVT__QueueCompatibility_30__DOT__ram_tl_state_size;
        VlUnpacked<CData/*6:0*/, 1> __PVT__QueueCompatibility_30__DOT__ram_tl_state_source;
        VlUnpacked<CData/*0:0*/, 1> __PVT__QueueCompatibility_30__DOT__ram_extra_id;
        VlUnpacked<CData/*3:0*/, 1> __PVT__QueueCompatibility_31__DOT__ram_tl_state_size;
        VlUnpacked<CData/*6:0*/, 1> __PVT__QueueCompatibility_31__DOT__ram_tl_state_source;
        VlUnpacked<CData/*0:0*/, 1> __PVT__QueueCompatibility_31__DOT__ram_extra_id;
    };

    // LOCAL VARIABLES
    CData/*3:0*/ QueueCompatibility__DOT____Vlvbound1;
    CData/*6:0*/ QueueCompatibility__DOT____Vlvbound2;
    CData/*0:0*/ QueueCompatibility__DOT____Vlvbound3;
    CData/*3:0*/ QueueCompatibility_1__DOT____Vlvbound1;
    CData/*6:0*/ QueueCompatibility_1__DOT____Vlvbound2;
    CData/*0:0*/ QueueCompatibility_1__DOT____Vlvbound3;
    CData/*3:0*/ QueueCompatibility_2__DOT____Vlvbound1;
    CData/*6:0*/ QueueCompatibility_2__DOT____Vlvbound2;
    CData/*0:0*/ QueueCompatibility_2__DOT____Vlvbound3;
    CData/*3:0*/ QueueCompatibility_3__DOT____Vlvbound1;
    CData/*6:0*/ QueueCompatibility_3__DOT____Vlvbound2;
    CData/*0:0*/ QueueCompatibility_3__DOT____Vlvbound3;
    CData/*3:0*/ QueueCompatibility_4__DOT____Vlvbound1;
    CData/*6:0*/ QueueCompatibility_4__DOT____Vlvbound2;
    CData/*0:0*/ QueueCompatibility_4__DOT____Vlvbound3;
    CData/*3:0*/ QueueCompatibility_5__DOT____Vlvbound1;
    CData/*6:0*/ QueueCompatibility_5__DOT____Vlvbound2;
    CData/*0:0*/ QueueCompatibility_5__DOT____Vlvbound3;
    CData/*3:0*/ QueueCompatibility_6__DOT____Vlvbound1;
    CData/*6:0*/ QueueCompatibility_6__DOT____Vlvbound2;
    CData/*0:0*/ QueueCompatibility_6__DOT____Vlvbound3;
    CData/*3:0*/ QueueCompatibility_16__DOT____Vlvbound1;
    CData/*6:0*/ QueueCompatibility_16__DOT____Vlvbound2;
    CData/*0:0*/ QueueCompatibility_16__DOT____Vlvbound3;
    CData/*3:0*/ QueueCompatibility_17__DOT____Vlvbound1;
    CData/*6:0*/ QueueCompatibility_17__DOT____Vlvbound2;
    CData/*0:0*/ QueueCompatibility_17__DOT____Vlvbound3;
    CData/*3:0*/ QueueCompatibility_18__DOT____Vlvbound1;
    CData/*6:0*/ QueueCompatibility_18__DOT____Vlvbound2;
    CData/*0:0*/ QueueCompatibility_18__DOT____Vlvbound3;
    CData/*3:0*/ QueueCompatibility_19__DOT____Vlvbound1;
    CData/*6:0*/ QueueCompatibility_19__DOT____Vlvbound2;
    CData/*0:0*/ QueueCompatibility_19__DOT____Vlvbound3;
    CData/*3:0*/ QueueCompatibility_20__DOT____Vlvbound1;
    CData/*6:0*/ QueueCompatibility_20__DOT____Vlvbound2;
    CData/*0:0*/ QueueCompatibility_20__DOT____Vlvbound3;
    CData/*3:0*/ QueueCompatibility_21__DOT____Vlvbound1;
    CData/*6:0*/ QueueCompatibility_21__DOT____Vlvbound2;
    CData/*0:0*/ QueueCompatibility_21__DOT____Vlvbound3;
    CData/*3:0*/ QueueCompatibility_22__DOT____Vlvbound1;
    CData/*6:0*/ QueueCompatibility_22__DOT____Vlvbound2;
    CData/*0:0*/ QueueCompatibility_22__DOT____Vlvbound3;

    // INTERNAL VARIABLES
    VysyxSoCFull__Syms* vlSymsp;  // Symbol table

    // CONSTRUCTORS
  private:
    VL_UNCOPYABLE(VysyxSoCFull_AXI4UserYanker_1);  ///< Copying not allowed
  public:
    VysyxSoCFull_AXI4UserYanker_1(const char* name);
    ~VysyxSoCFull_AXI4UserYanker_1();

    // INTERNAL METHODS
    void __Vconfigure(VysyxSoCFull__Syms* symsp, bool first);
} VL_ATTR_ALIGNED(VL_CACHE_LINE_BYTES);

//----------


#endif  // guard
